export const OPEN_INNER = "OPEN_INNER"
export const CLOSE_INNER = "CLOSE_INNER"
export const SET_STATUS = 'SET_STATUS'
export const HANDLE_MAIN_TAB = "HANDLE_MAIN_TAB"
export const HANDLE_SUB_TAB = "HANDLE_SUB_TAB"
export const EDIT_LEAD = "EDIT_LEAD"
export const ADD_LEAD ="ADD_LEAD"
export const OPEN_BULK_MODAL = "OPEN_BULK_MODAL"
export const CLOSE_BULK_MODAL ="CLOSE_BULK_MODAL"
export const OPEN_ASSIGN_MODAL = "OPEN_ASSIGN_MODAL"
export const CLOSE_ASSIGN_MODAL= "CLOSE_ASSIGN_MODAL"
export const ASSIGN_LEAD = "ASSIGN_LEAD"
export const OPEN_FORM ="OPEN_FORM"
export const CLOSE_FORM = "CLOSE_FORM"
export const CHANGE_INPUT= "CHANGE_INPUT"


